"""empty message

Revision ID: 02ed5117ac1d
Revises: 1ebb85349468
Create Date: 2025-04-23 20:22:08.197123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02ed5117ac1d'
down_revision = '1ebb85349468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recommended_for', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('image', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('image')
        batch_op.drop_column('recommended_for')

    # ### end Alembic commands ###
