"""empty message

Revision ID: 1ebb85349468
Revises: 1bf3af337876
Create Date: 2025-04-22 22:16:48.697474

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ebb85349468'
down_revision = '1bf3af337876'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('duration', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('location', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('includes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('benefits', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('important_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('important_notes')
        batch_op.drop_column('benefits')
        batch_op.drop_column('includes')
        batch_op.drop_column('location')
        batch_op.drop_column('duration')

    # ### end Alembic commands ###
