"""Add booking_url to Service

Revision ID: 882f14434c50
Revises: 5c512f03a2ad
Create Date: 2024-12-09 20:26:06.824331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '882f14434c50'
down_revision = '5c512f03a2ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service', schema=None) as batch_op:
        batch_op.drop_column('booking_url')

    # ### end Alembic commands ###
